# Generated by Django 4.2.30 on 2026-05-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maxsulot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='maxsulot/')),
                ('category', models.CharField(choices=[('nonlar', 'yangi maxsulot'), ('pishiriqlar', 'sutlar'), ('tortlar', 'biskivitlar')], default='non maxsulotlar', max_length=20)),
            ],
        ),
    ]
